version: "3"
services:
    web1:
        depends_on:
            - "redis_image"
            - "web2"
            - "web3"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=development
        links:
            - "redis_image"
            - "web2"

            
    web2:
        depends_on:
            - "redis_image"
        build:
            context: ./PAMiW_REST
            dockerfile: Dockerfile
        ports:
            - "8081:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=development
        links:
            - "redis_image"

    web3:
        depends_on:
            - "redis_image"
        build:
            context: ./PAMiW_PDF
            dockerfile: Dockerfile
        ports:
            - "8082:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=development
        links:
            - "redis_image"

    redis_image:
        image: redis
        container_name: cache
        ports:
        - "6379:6379"